# Generated by Django 3.0.2 on 2020-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='Date',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='expenses',
            name='FY',
            field=models.CharField(choices=[('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Image',
            field=models.FileField(blank=True, unique=True, upload_to=''),
        ),
    ]
