# Generated by Django 3.0.2 on 2020-02-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_auto_20200215_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='FY',
            field=models.CharField(choices=[('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024')], default='Please Select', max_length=50),
        ),
    ]
