# Generated by Django 3.0.4 on 2020-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0003_auto_20200215_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='FY',
            field=models.CharField(choices=[('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024')], default='', max_length=50),
        ),
    ]
