# Generated by Django 3.0.4 on 2020-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0005_auto_20200413_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Category',
            field=models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing'), ('Meeting', 'Meeting'), ('Admin', 'Admin'), ('Fees', 'Fees'), ('Lawyer', 'Lawyer'), ('Marketing', 'Marketing'), ('Store', 'Store'), ('Brokage', 'Brokage'), ('Travel', 'Travel'), ('Bank Statement', 'Bank Statement')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='FY',
            field=models.CharField(choices=[('2018', '2018'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024')], default='', max_length=50),
        ),
    ]
